export enum ValidType {
  NO_SPACE = 'NO_SPACE',
  NO_MANY_SPACE = 'NO_MANY_SPACE',
  IS_STRING = 'IS_STRING',
  IS_NUMBER = 'IS_NUMBER',
  NO_SPECIAL_CHARACTER = 'NO_SPECIAL_CHARACTER',
  IS_EMAIL = 'IS_EMAIL',
  SPECIAL_CHARACTER = 'SPECIAL_CHARACTER',
  MINIMUM_ONE_NUMBER_STRING_SPECIAL_CHARACTER = 'MINIMUM_ONE_NUMBER_STRING_SPECIAL_CHARACTER',
}

export enum AccessProfile {
  COMMON = 'Analista',
  ADMIN = 'Administrador',
}
